In [3]:
from NNetwork import NNetwork as nn

edgelist = [[1,2],[2,3],[3,4]]
G = nn.NNetwork()
G.add_edges(edgelist)

A = G.get_adjacency_matrix()
print(A)

V = G.nodes()
print(f"\nnodes: {V}")

neigh_2 = G.neighbors('2')
print(f"\nthis is node 2's neighbors {neigh_2}")

print(G.has_edge('2','3'))

[[0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]]

nodes: ['1', '2', '3', '4']

this is node 2's neighbors {'1', '3'}
True


In [36]:
edgelist2 = [[2,3],[3,4],[5,7]]
G2 = nn.NNetwork()
G2.add_edges(edgelist2)

print(G.intersection(G2))


[['3', '4'], ['3', '2'], ['4', '3'], ['2', '3']]


In [51]:
### Weighted Graph
edgelist = [[1,2,0.5],[2,3, 0.8]]
G = nn.NNetwork()
G.add_edges(edgelist)

A = G.get_adjacency_matrix()
print(A)

w = G.get_edge_weight(2,3)
print(w)

# Convert to an unweighted graph
G_simple = G.threshold2simple(0.4)
print(f"\n{G_simple.nodes()}")

A_simple = G_simple.get_adjacency_matrix()
print(A_simple)

[[0.  0.5 0. ]
 [0.5 0.  0.8]
 [0.  0.8 0. ]]
0.8

['1', '2', '3']
[[0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]


In [61]:
### Mesoscale Patch computation
edgelist = [[1,2],[2,3],[1,3],[1,4],[1,5]]
G = nn.NNetwork()
G.add_edges(edgelist)
print(f"Nodes: {G.vertices}")

print(f"\nEdges: {G.edges}")

X, embs = G.get_patches(k=3, sample_size=4, skip_folded_hom=False)
print(f"\nVec_patches: \n{X}") # each column is a vectorizaiton of k x k induced adjacency matrix

print(f"\nWalk:{embs}") # four consecutive 3-walks in G


Nodes: ['1', '2', '3', '4', '5']

Edges: {"['1', '2']": 1, "['2', '1']": 1, "['2', '3']": 1, "['3', '2']": 1, "['1', '3']": 1, "['3', '1']": 1, "['1', '4']": 1, "['4', '1']": 1, "['1', '5']": 1, "['5', '1']": 1}

Vec_patches: 
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]

Walk:[array(['2', '1', '3'], dtype='<U32'), array(['3', '1', '3'], dtype='<U32'), array(['2', '3', '2'], dtype='<U32'), array(['3', '1', '4'], dtype='<U32')]


In [62]:
import numpy as np
A = np.array([[2,3],
              [1,2],
              [6,9]])
A = np.asarray(A)
print(A)

[[2 3]
 [1 2]
 [6 9]]


In [67]:
import numpy as np

# Example setup: Creating an array of arrays, each with a shape of (3, 4)
A = np.array([np.random.randint(0, 10, (3, 4)) for _ in range(5)])

# Each element of A is a (3, 4) array
print("Each element shape:", A[0].shape)
print("Example element:\n", A[0])

# Horizontally stack the arrays from the list to form a (3, 20) matrix
result_matrix = np.hstack(A)

print("Resulting matrix shape:", result_matrix.shape)
print("Resulting matrix:\n", result_matrix)


Each element shape: (3, 4)
Example element:
 [[3 9 9 1]
 [5 5 5 0]
 [1 1 2 4]]
Resulting matrix shape: (3, 20)
Resulting matrix:
 [[3 9 9 1 6 5 6 9 5 0 0 3 6 8 8 8 6 6 3 0]
 [5 5 5 0 0 6 4 5 5 9 5 5 7 1 0 6 3 7 5 6]
 [1 1 2 4 6 7 7 7 2 4 2 8 6 7 3 2 1 2 5 7]]


In [72]:
A = np.array([[2,3],[4,9], [8,10]])
A = A.reshape(1,-1)
A = A[0]
print(A)

[ 2  3  4  9  8 10]


In [1]:
from NNetwork import NNetwork as nn
G_fly = nn.NNetwork()
G_fly.load_add_edges("data/bn-fly-drosophila_medulla_1.txt", 
                     use_genfromtxt=True, delimiter=",")

In [ ]:
from src.NDL.ndl_test import NetDictLearner

NDL_fly_3 = NetDictLearner(G=G_fly, n_components=9, k=7)
NDL_fly_3.train_dict()

In [1]:
import numpy as np

# 1D array
a = np.array([1, 2, 3, 4, 5])

# Convert to a row vector using np.newaxis
row_vector = a[np.newaxis, :]

# Convert to a column vector using np.newaxis
column_vector = a[:, np.newaxis]

print("Row Vector:\n", row_vector)
print("Column Vector:\n", column_vector)


Row Vector:
 [[1 2 3 4 5]]
Column Vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [2]:
import numpy as np

# Creating example arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Concatenating along the first axis (0), rows are added
concatenated_array1 = np.concatenate((array1, array2), axis=0)

# Creating another example for axis 1 concatenation
array3 = np.array([[7, 8], [9, 10]])

# Concatenating along the second axis (1), columns are added
concatenated_array2 = np.concatenate((array1, array3), axis=1)

print("Concatenated along rows:\n", concatenated_array1)
print("Concatenated along columns:\n", concatenated_array2)

Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]]
Concatenated along columns:
 [[ 1  2  7  8]
 [ 3  4  9 10]]


In [7]:
import numpy as np

a = np.array([1,2,3,4,5,6])

a= a.reshape(-1,1)
print(a.shape)

(6, 1)
